version: '3.5'
services:
  mysql-server:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_ROOT_PASSWORD=zabbix_root
    command: ['mysqld','--character-set-server=utf8','--collation-server=utf8_bin','--default-authentication-plugin=mysql_native_password']
    deploy:
      placement:
        constraints:
          - node.labels.zabbixrole == server
      restart_policy:
        condition: on-failure

  #zabbix-java-gateway:
  #  image: zabbix/zabbix-java-gateway:latest
  #  restart: unless-stopped

  zabbix-server-mysql:
    image: zabbix/zabbix-server-mysql:latest
    environment:
      - DB_SERVER_HOST=mysql-server
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_ROOT_PASSWORD=zabbix_root
      #- ZBX_JAVAGATEWAY=zabbix-java-gateway
    depends_on:
      - 'mysql-server:mysql'
      #- 'zabbix-java-gateway:zabbix-java-gateway'
    ports:
      - '10051:10051'
    deploy:
      placement:
        constraints:
          - node.labels.zabbixrole == server
      restart_policy:
        condition: on-failure

  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql:latest
    environment:
      - DB_SERVER_HOST=mysql-server
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_ROOT_PASSWORD=zabbix_root
    depends_on:
      - 'mysql-server:mysql'
      - 'zabbix-server-mysql:zabbix-server'
    ports:
      - '80:8080'
    restart: unless-stopped
    deploy:
      placement:
        constraints:
          - node.labels.zabbixrole == server
      restart_policy:
        condition: on-failure

  zabbix-agent:
    image: zabbix/zabbix-agent:latest
    depends_on:
      - 'mysql-server:mysql'
      - 'zabbix-server-mysql:zabbix-server'
    environment:
      - 'ZBX_HOSTNAME=Zabbix server'
      - ZBX_SERVER_HOST=zabbix-server
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
